export enum PhotoSessionStatus {
  NEW_PHOTO_SESSION,

  CLIENT_FILLED_THE_BRIEF,

  ONE_DAY_TO_PHOTO_SESSION,

  PHOTOGRAPHER_FINISHED_PHOTO_SESSION,

  PHOTOGRAPHER_UPLOADED_PHOTOS_FIRST_TIME,

  CLIENT_CHOSE_PHOTOS,

  PHOTOGRAPHER_UPLOADED_PHOTOS_SECOND_TIME,

  CLIENT_DOWNLOADED_PHOTOS,

  MANAGER_FINISHED_PHOTO_SESSION
}
